### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/anaconda/conda-bld/osx-64'

### ISSUE THREAD

**Issue by dkoppstein** [bioconda/recipes#169]
Hi, I was just updating a new recipe, but when I ran the docker command manually I found that I got 

```
ubuntu@ip-10-156-12-254:~/src/github.com/dkoppstein/recipes$ sudo docker run -v `pwd`:/bioconda-recipes bioconda/bioconda-builder --packages seqtk
updating index in: /anaconda/conda-bld/linux-64
updating index in: /anaconda/conda-bld/osx-64
Traceback (most recent call last):
  File "/anaconda/bin/conda-index", line 5, in <module>
    sys.exit(main())
  File "/anaconda/lib/python3.4/site-packages/conda_build/main_index.py", line 59, in main
    check_md5=args.check_md5, remove=args.remove)
  File "/anaconda/lib/python3.4/site-packages/conda_build/index.py", line 72, in update_index
    files = set(fn for fn in os.listdir(dir_path) if fn.endswith('.tar.bz2'))
FileNotFoundError: [Errno 2] No such file or directory: '/anaconda/conda-bld/osx-64'
Reading recipe /bioconda-recipes/recipes/seqtk
E
======================================================================
ERROR: __main__.test_recipes('/bioconda-recipes/recipes/seqtk',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/bioconda-recipes/scripts/build-packages.py", line 57, in build_recipe
    conda_index()
  File "/bioconda-recipes/scripts/build-packages.py", line 51, in conda_index
    sp_call = sp.check_call(["conda", "index"] + index_dirs)
  File "/anaconda/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'index', '/anaconda/conda-bld/linux-64', '/anaconda/conda-bld/osx-64']' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 1 test in 1.744s

FAILED (errors=1)
```

I'm surprised by this, because I see in the Dockerfile that /anaconda/conda-bld/osx-64 is explicitly made. Further, the conda build command passes and Travis successfully built the package as well.

**Comment by daler** [comment]
There were some recent changes to the dockerfile, one of which included making that directory -- does it work after doing a `docker pull bionconda/bioconda-builder`?

**Comment by dkoppstein** [comment]
Yes, it works -- thanks! Sorry, still quite new to Docker, thanks for pointing me in the right direction.
